name: schedule-event

on:
  schedule:
    # 10:00 AM on JST
    # - cron: '0 1 * * *'
    # 02:00 PM on JST
    # - cron: '0 5 * * *'
    # 06:00 PM on JST
    # - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  schedule-event:
    runs-on: ubuntu-latest

    steps:
      - name: Main
        run: date
